-- Generated by generateTrackSql.ts
-- Source: Google Drive folder 1mCazOsvAhViKaAc1md_IEgk7NNDX5-rl
-- Run this in Supabase SQL Editor

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Never Let You Go (175)',
  '12. Rudimental ft Foy Vance',
  '',
  'clean',
  'C#m',
  89,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Jelly (Intro',
  'Andre Nickatina',
  'Clean)',
  'clean',
  'F#m',
  97,
  'Hip Hop',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Daylight (Original Mix)',
  'Andrew Rayel feat. Jonny Rose',
  '',
  'clean',
  'Am',
  128,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Rock DJ (Saccao & West.K Remix)',
  'Andrey Exx, Diva Vocal, Troitski',
  '',
  'clean',
  'Em',
  122,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Rock DJ (Saccao & West.K Remix) [www.MARVIN-VIBEZ.to]',
  'Andrey Exx, Diva Vocal, Troitski',
  '',
  'clean',
  'Em',
  122,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Fall Down feat. Angelika Vee (Original Mix) [Revealed Recordings]',
  'Angelika Vee, Spencer Tarring',
  '',
  'clean',
  'D#',
  128,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Another You (Headhunterz Remix) - F#m - 128',
  'Another You (Headhunterz Remix)',
  '',
  'clean',
  'F#m',
  128,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'F#m',
  'Apollo _ Dj Freefall Edit',
  '',
  'clean',
  'F#m',
  0,
  'Top 40',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Rising Love (Original Mix)',
  'Arno Cost & Norman Doray feat. Mike Taylor',
  '',
  'clean',
  'F#m',
  126,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Dynamite [www.MARVIN-VIBEZ.to]',
  'Art Brothers vs Quintino & MOTi',
  '',
  'clean',
  'C#m',
  128,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Get Stupid (Chris Lake Remix)',
  'Aston Merrygold',
  '',
  'clean',
  'Dm',
  125,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'All About Him',
  'Auburn',
  '',
  'clean',
  '',
  0,
  'Top 40',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Waiting For Love - Carnage & Headhunterz Remix',
  'Avicii',
  '',
  'clean',
  '',
  0,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Waiting For Love',
  'Avicii',
  'Sam Feldt Remix',
  'clean',
  'F#m',
  126,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Rave (Original)Emaj',
  'Ayjay',
  '',
  'clean',
  'Fm',
  0,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Back That Azz Up (Audiorokk Get''em outta Twerk Aca Edit) - Dm - 100',
  'Back That Azz Up (Audiorokk Get''em outta Twerk Aca Edit)',
  '',
  'clean',
  'Dm',
  100,
  'Twerk / Bass',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Beggin For Thread (SALVA Remix) [djmebbe.com]',
  'Banks',
  '',
  'clean',
  '',
  0,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Im In A State Of Trance (Asot 750 Anthem) (Radio Edit) [mp3clan.com]',
  'Ben Gold',
  '',
  'clean',
  '',
  0,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Fall With Me (Original Mix) [mp3clan.com]',
  'Ben Gold Feat. The Glass Child',
  '',
  'clean',
  '',
  0,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Partition - Electric Bodega Remix - Fm or Cm',
  'Beyonce',
  '',
  'clean',
  '',
  99,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Crazy In Love (Club Killers Remix) CK Final',
  'Beyonce ft Jay Z',
  '',
  'clean',
  'A#',
  99,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Beyonce ft.Jay-Z-Drunk in love(Diplo remix)(djGraff ext mix)  - Fm - 140',
  'Beyonce ft.Jay-Z-Drunk in love(Diplo remix)(djGraff ext mix)',
  '',
  'clean',
  'Fm',
  140,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'IDFWU (STARJACK HYPE RE-DRUM ) cln',
  'BIG SEAN',
  '',
  'clean',
  'D#m',
  100,
  'Hip Hop',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'BITCH IM MADONNA (WEDDING CRASHERZ HYPE SUM UP) [DIRTY] - D#m - 150',
  'BITCH IM MADONNA (WEDDING CRASHERZ HYPE SUM UP) [DIRTY]',
  '',
  'dirty',
  'D#m',
  150,
  'Hip Hop',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Yesterday (Dj Jay Intro) (Dirty)',
  'Black Eyed Peas',
  '',
  'dirty',
  'Cm',
  106,
  'Hip Hop',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'How You Like That(AJ Remix)',
  'BLACKPINK',
  '',
  'clean',
  '',
  0,
  'K-Pop',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Born In The USA (Audiorokk Melbourne Bootleg) - Fm - 128',
  'Born In The USA (Audiorokk Melbourne Bootleg)',
  '',
  'clean',
  'Fm',
  128,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Cali (Tunnelmental Experimental Assembly Remix) - Bm - 128',
  'Cali (Tunnelmental Experimental Assembly Remix)',
  '',
  'clean',
  'Bm',
  128,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Calling Arcadia (JonahJordan Edit) - F#m - 128',
  'Calling Arcadia (JonahJordan Edit)',
  '',
  'clean',
  'F#m',
  128,
  'Top 40',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  '5 AM (DJ FmSteff 2015 Totalmix)',
  'Calvin Harris ft Tinashe',
  '',
  'clean',
  'C#m',
  144,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Toca',
  'Carnage feat. Timmy Trumpet & KSHMR',
  '',
  'clean',
  'Dm',
  128,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'See You Again (Adam Foster Remix) [www.MARVIN-VIBEZ.to]',
  'Charlie Puth X Wiz Khalifa',
  '',
  'clean',
  'A#',
  109,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'FINE CHINA (STARJACK HYPE PARTY STARTER) cln',
  'CHRIS BROWN',
  '',
  'clean',
  'D#m',
  104,
  'Hip Hop',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Came to do',
  'Chris Brown ft. Akon',
  '',
  'clean',
  'D# or Gm',
  98,
  'Hip Hop',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Came to do [www.MARVIN-VIBEZ.to]',
  'Chris Brown ft. Akon',
  '',
  'clean',
  'D# or Gm',
  98,
  'Hip Hop',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Ayo',
  'Chris Brown ft. Tyga',
  '',
  'clean',
  'F#',
  98,
  'Hip Hop',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Ayo [www.MARVIN-VIBEZ.to]',
  'Chris Brown ft. Tyga',
  '',
  'clean',
  'F#',
  98,
  'Hip Hop',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Piano Hand (Original Mix) [Ultra]',
  'Chris Lake, Chris Lorenzo',
  '',
  'clean',
  'Fm',
  126,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Withdrawal (Intro)',
  'Chris Lawrence',
  '',
  'clean',
  'A#m',
  94,
  'Top 40',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Jidenna (ft Kendrick Lamar)',
  'Classic Man',
  'STR8CUT-1.0 /  /',
  'clean',
  'Gm',
  94,
  'Hip Hop',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Higher (DJ REG Extended)',
  'Classified',
  '',
  'clean',
  'D',
  92,
  'Top 40',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Cancun X (Original Mix) Clean',
  'Club Killers',
  '',
  'clean',
  'Dm',
  125,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'You Know You Like It',
  'DJ Snake & AlunaGeorge',
  '',
  'clean',
  'Cm',
  0,
  'Top 40',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'The Sun, The Moon, The Stars (Embody Remix)',
  'Copy Club',
  '',
  'clean',
  'G#m',
  121,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Liar Liar',
  'Cris Cab ft Pharrell',
  '',
  'clean',
  'Dm',
  107,
  'Top 40',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Bad Chick (DJ REG Extended)',
  'Cro',
  '',
  'clean',
  'F#',
  102,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'B-boy (Clean)',
  'Crown City Rockers',
  '',
  'clean',
  'Bm',
  89,
  'Electronic',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Cupid Shuffle - Teach Me How To Dougie (Segue - Trans 72-85 - Dirty) - Gm or Dm',
  'Cupid x Cali Swag District',
  '',
  'dirty',
  '',
  88,
  'Hip Hop',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Keep Giving Me Love (Short Edit)',
  'D Train',
  '',
  'clean',
  'Dm',
  123,
  'R&B',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);

INSERT INTO tracks (title, artist, version, version_type, key, bpm, genre, price, artwork_url, is_new, is_hot, created_at, updated_at)
VALUES (
  'Cha Cha (Deville Cha Cha Slide Party Break) Clean 4A 67',
  'D.R.A.M. x DJ Casper',
  '',
  'clean',
  'Fm',
  135,
  'Top 40',
  1.99,
  'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&h=600&fit=crop',
  true,
  false,
  NOW(),
  NOW()
);
